# Generated by Django 5.1.3 on 2024-11-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
        migrations.AddField(
            model_name='weapon',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
